project:
  type: site

site:
  title: "Quarto Observable"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Main"
        contents:
          - index.qmd
          - section: Features
            contents:
              - features/javascript.qmd
              - features/not-javascript.qmd
              - features/reactive-values.qmd
              - features/file-attachments.qmd
              - features/observable-modules.qmd
              - section: "ES6"
                contents:
                - module-tests/es6-module-import.qmd
                - module-tests/module-import-2.qmd
      - section: "Tests"
        contents:
          - tests/index.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-tools: true

